/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutPage: typeof import('./src/components/AboutPage.vue')['default']
    ConnectPage: typeof import('./src/components/ConnectPage.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    NotFoundPage: typeof import('./src/components/NotFoundPage.vue')['default']
    ProjectsPage: typeof import('./src/components/ProjectsPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillsPage: typeof import('./src/components/SkillsPage.vue')['default']
  }
}
