#!/bin/sh
set -ex

cd /app

(
    if [ -f .env ]; then
        source .env
    fi

    if [ "$APP_ENV" != "local" ]; then
        php artisan config:cache
    else
        composer install \
            --ignore-platform-reqs \
            --no-interaction \
            --no-progress \
            --no-suggest
        php artisan config:clear
    fi

    if [ -L public/storage ]; then
        rm public/storage
    fi
    php artisan storage:link

    if [ "$DB_FRESH_ON_START" = "true" ]; then
        php artisan migrate:fresh
        php artisan db:seed
    else
        php artisan migrate --force
    fi
)

exec php artisan octane:start --no-interaction --host=0.0.0.0
